### ISSUE TITLE
Refactor Project Serialization

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1136]
in the current approach there are several things that could be refactored:
1. separate the external import/export data representation from the internal one that would simplify upwards compatibility
2. why an xml file per perspective?
3. implement some simple range compression to compress the VirtualArrayList as there are a lot of continuous integer values (or at least the XmlList annotation)
4. why do we store the original raw data, even if e.g. just a few columns are used, even more critical for further developments were e.g. R data is loaded
5. consistent handling of categorical pseudo perspectives, e.g. the mutation ones,...
6. what about using xml attributes for required fields, e.g. boolean isPrivate

**Comment by alexsb** [comment]
1 We decided up to now that we don't care about compatibility at this point. The main goal is to keep it simple for us to maintain. We will eventually have to change this policy, but I'm not sure whether this is the time
 2 probably mainly historic reasons. Is this a disadvantage?
 3 sure, but is it worth the effort?
 4 because we could want to add additional parameters in an analysis (e.g., add a column). Granted, not very likely, could be removed.
 6 what do you mean? To verify whether the required fields are there? Yes, makes sense, but again cost-benefit?

**Comment by sgratzl** [comment]
> 1 We decided up to now that we don't care about compatibility at this point. The main goal is to keep it simple for us to maintain. We will eventually have to change this policy, but I'm not sure whether this is the time

I think we should rethink our policy, to be upward compatible. such that people can open old tcga packages with the latest version of caleydo

> 2 probably mainly historic reasons. Is this a disadvantage?

if we use some kind of compression the overhead of many files would be too high to the benetift as the files becoming quite small. 

> 3 sure, but is it worth the effort?

in 38aada2cc7b5da153be4decc0b3191340f09eaef I already commited a simple approach

> 4 because we could want to add additional parameters in an analysis (e.g., add a column). Granted, not very likely, could be removed.

the main problem is if we realize #1132 there won't be any CSV file that could be serialized.

> 6 what do you mean? To verify whether the required fields are there? Yes, makes sense, but again cost-benefit?

it would just reduce the project size, with the effort to use the `@XmlAttribute` annotation

related to #1132
