### ISSUE TITLE
persisting/saving state should not include Tour Guide

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1160]
Saving takes way too long (seems like it is not progressing at all).

**Comment by sgratzl** [comment]
up to now the tour guide state won't be persisted

the reason is not tourguide but the storing of all the table perspectives of the mutation and copy number data

the current implementation avoids creating all the table perspectives but creates them lazy if you add them to stratomex. That means only the copy number / mutations rows that were once shown in stratomex will be stored

**Comment by sgratzl** [comment]
@ngehlenborg please check if that is sufficient for you

**Comment by ngehlenborg** [comment]
Works in 08c69967aabe7124513d992150782735e038f244. Closing.
