### ISSUE TITLE
change perspective to open Tour Guide view next to StratomeX

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1162]
Users unfamiliar with the framework will have a hard time figuring out that they can change the view configuration by dragging around tabs.

**Comment by sgratzl** [comment]
duplicate to #1157 and/or #1133

**Comment by ngehlenborg** [comment]
It's unclear to me what the resolution is (too many tickets are referenced!). #1133 reads like it is resolved, but it is still open.

**Comment by sgratzl** [comment]
> It's unclear to me what the resolution is (too many tickets are referenced!). #1133 reads like it is resolved, but it is still open.

the problem is that I can't find a way to realize #1133 without any problems. The reason might be that we are using the compatibility layer of eclipse ( see #1138, which should fix that). 

My current solution (which I want to test) is to put tourguide at the bottom similar to the search view / console view in eclipse, because as far as I remember at this position it will work.
