### ISSUE TITLE
Can't run Caleydo/LineUp on Montain Lion

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1173]
Having exactly the problem described here:

https://discussions.apple.com/thread/4706882?start=0&tstart=0

**Comment by sgratzl** [comment]
related #1185

**Comment by sgratzl** [comment]
is there anything that we can do, otherwise it's a invalid ticket for me

**Comment by alexsb** [comment]
We should try this with a release candidate (I suspect that it is fixable, at least for starting from command line)  and publish a description on how to fix it on the website.

**Comment by ngehlenborg** [comment]
I have managed to run Caleydo 3.0 successfully on two different Macs. However, in order to launch the application with the binary launcher or from the the command line (by calling Caleydo.app/Content/MacOS/Caleydo) the Oracle Java JDK 1.7 has to be installed. The JRE (what you get when downloading Java from java.com) is not sufficient, because it does not update the java -version symlinks or add java to the path: "Installing a JRE from Oracle will not update java -version symlinks or add java to your path. To be able to do this, you need to install the JDK."(http://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jre.html)
