### ISSUE TITLE
Do we have alternatives to GSEA?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1195]
GSEA is very slow. 
@ngehlenborg Do we have alternatives to the classic GSEA which might even work better? How about pGSEA (would be much faster as well)?

**Comment by sgratzl** [comment]
related #920 

PGSEA (Parametric Gene Set Expression Analysis), based on http://www.biomedcentral.com/1471-2105/6/144 and R package http://bioconductor.org/packages/2.4/bioc/html/PGSEA.html

**Comment by ngehlenborg** [comment]
The biggest issue is probably that we only have 1500 genes (in most cases), which will lead to very poor results no matter what method we are using, because we only have data for a small fraction of the genes in each pathway.

We probably have to load the full expression matrix (> 100 MB) for such calculations. Lets discuss this in our next call.

##

**Comment by ngehlenborg** [comment]
See also #1491.

**Comment by alexsb** [comment]
We'll do GSA, see #1491. Closing
