### ISSUE TITLE
Where are the heatmaps for the copy number dataset coming from?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1366]
I just loaded a grouping onto the copy number data (by accident) and when I added it to stratomex (via DVI, it does not show up in LineUp) I actually got heatmaps. They make  perfect sense but I have no clue where the data shown in those heatmaps is coming from. 

![screen shot 2013-06-30 at 7 42 54 pm](https://f.cloud.github.com/assets/1216518/728044/ddc24e26-e1de-11e2-9b73-98d4a18a4448.png)

**Comment by alexsb** [comment]
This looks like you loaded a gene grouping for copy number? If you want an answer you need to provide details ;).

**Comment by ngehlenborg** [comment]
Sample grouping.

**Comment by alexsb** [comment]
I don't understand the problem. Of course you can load heat maps for copy number data. You always could, they were typically yellow because of the heat map bug. Here's an example I created with the Verhaak subtypes:

![feature](https://f.cloud.github.com/assets/2039375/732540/213745a2-e285-11e2-8bfd-5f2de94eb6f5.png)
