### ISSUE TITLE
No scores are computed for genes/stratification that are already included in another view

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1371]
It looks like no scores are computed for genes/stratification that are already included in another view (the ones at the bottom from BRAF to NRAS).

![screen shot 2013-07-01 at 11 29 40 am](https://f.cloud.github.com/assets/1216518/731057/4f7a520a-e263-11e2-9af2-c85cd9634d58.png)

**Comment by sgratzl** [comment]
comming from #1274

**Comment by sgratzl** [comment]
is this reliable reproducable or just once by chance?

>  genes/stratification that are already included in another view 

= brick in other StratomeX instances?

**Comment by ngehlenborg** [comment]
It does not happen when I am working with a "fresh" project (i.e. one that was not loaded from a "Save Project" cal file). 

In the case reported above the problem occurred when I was working with a cal file generated with "Save Project". Due to the issues related to loading cal files I am unable to test this at the moment.
