### ISSUE TITLE
Redesign PathwayTablePerspective

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1389]
PathwayTablePerspective is deprecated and rightfully so. Here are some design alternatives:

Provide a defined field in the TablePerspectives where additional information can be held. Specifically, this would be a reference to the pathway datadomain and the specific pathway, but could equally be information about the type of data (e.g., is it data that should be shown as KM plots). 

This would also mean that such a new pathway table perspective is a fully independent TablePerspective which is stored in and primarily associated with the ATableBasedDataDomain.

The biggest disadvantage of this approach is that it essentially limits us to one pathway per column, as we can't allow multiple pathways for one table perspective, as we did in the original pathway implementation. Therefore we have to make the decision that we do not intend to show multiple pathways in one column. 

The alternative would be to use a PathwayPerspecive which holds (not inherits) a TablePerspective. This would associated the perspective primarily with the pathway DD. The biggest disadvantage is that this is very different from what we have now and would probably require a joint super-type of the PathwayPerspective and the  TablePerspective.

It should also be noted that we don't serialize table-perspectives at all at the moment. They are always dynamically generated based on a record and dimension perspecitve. However, this is also not ideal since computationally expensive statistics, for example, would have to be re-computed.

**Comment by sgratzl** [comment]
a third option would be to handle the pathways as a special table with pathway x vertices. Therefore a single pathway would be table perspective with a single column and x records, representing the contained vertices. pathway x genes might also work.

pros: 
- its just a table perspective without any special data
- mapping onto a pathway is an optional operation, which can be implemented as having two tableperspectives: one for the pathway, one for the mapped data
- one table perspective per pathway not one per pathway per mapped data

cons:
- pathway, enroute,.. would need to handle multiple table perspectives instead of one
