### ISSUE TITLE
Shouldn't the grouping import use the column header instead of the filename?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1428]
Usually the column header contains the name of the stratification. 
Also, if one imports multiple groupings from one file, the filename has no meaning.

**Comment by mstreit** [comment]
The problem is that we currently allow the user only assign and edit one grouping name. What happens if the user selects multiple columns?

**Comment by alexsb** [comment]
Afair the number of clusters is added. If no name is provided the parser assigns the title. (I'd have to check this though)

**Comment by alexsb** [comment]
Here is the current state: 

![grouping](https://f.cloud.github.com/assets/2039375/835933/81beee32-f2e5-11e2-9c59-3a18d1f158cf.png)

Right now I take the "Grouping Name" and add the number of clusters. This would be "cnmf.membership 3" in this case for the first column. We have a couple of options here: 
- Keep it the way it is + add some explanation that the number of clusters is added to the name
- Add a radio to let a user choose to use the above behavior or use the column headers
- Give the user the ability to change the headers (this can be done on top of the previous point)

**Comment by sgratzl** [comment]
> Give the user the ability to change the headers (this can be done on top of the previous point) 

+1

Single column selected -> by default the data set name
multiple ones -> by default the column header

**Comment by mstreit** [comment]
agree with @sgratzl + brief description

**Comment by alexsb** [comment]
ok, @cpartl  - please implement the GUI, I'll take care of the back-end.

**Comment by cpartl** [comment]
ok, just to be sure what we need here:
- we need to specify, which row contains the grouping titles
- the user should be able to modify the text in this row
- upon confirmation the titles should be added to the grouping description (does not exist yet)

**Comment by alexsb** [comment]
Yes. We could also think about adding a row that's not yet there for the labels?

Also, I'm not so sure if we do want 

> Single column selected -> by default the data set name

This seems rather inconsistent. Maybe we should drop the dataset name altogether.

**Comment by cpartl** [comment]
Yes, we could add a dedicated row for that. But it could be inconvenient, if the information is already present in one of the rows. 
What about making this dedicated title row "moveable" , so that it is at the top with empty cells by default and when moving down, it is filled with the cell content of the underlying rows (just like a mask)?

I agree with dropping the dataset name.

**Comment by alexsb** [comment]
Maybe we can do an "add header row" instead?

**Comment by cpartl** [comment]
How should that work?

**Comment by alexsb** [comment]
A button labeled "add header row". If you press it a new row is added to the table with "Grouping 1" "Grouping 2"... in the cells.

**Comment by cpartl** [comment]
Yes, but this does not solve the problem of reusing the text already present in the dataset.
What about this:
You always see the dedicated header row, filled with "Grouping 1" etc by default.
To fill this row with the text of an existing row, we add a button "use as titles" to the headers of all rows, which copies their text. (or marks this row as header row)

**Comment by cpartl** [comment]
Of course this would be many buttons, maybe move that to the context menu, but this might be too subtle?

**Comment by cpartl** [comment]
gui is rfc, waiting for back-end

**Comment by alexsb** [comment]
Looks good, a couple of comments: 
- clicking on "use Custom Grouping Names" does add a new line every time
- maybe we don't even need this distinction? We could just have one "add header button" that does something similar to the "use custom grouping names" radio. Ideally you should be able to also directly edit the existing header line (i.e., make the green line editable). 
- Then the spinner could be active all the time then.

**Comment by alexsb** [comment]
OK, i've implemented a version of the back-end. Didn't test it though, since I didn't immediately see how to set the grouping names in save() of ImportGroupingDialog.

GroupingParseSpecification now has a list of groupingNames. Right now I use the groupingNames or an automatically generated string. It would be possible to use a row of the file too, but this seems unnecessary given the way you'd have to implement this in the GUI?

**Comment by cpartl** [comment]
I chose to implement it that way for a couple of reasons:
- A simple push button suggests that you could add such a line more than one time
- You can not remove the added line again without another widget (you could use a checkbox of course, but radio is better, see below)
- You generally either want to use existing grouping names from a header line, or a custom one (being because there is no header line, or the header line is not suitable)
- Editing within the body of the table might suggest that you can actually edit the file. The behavior of changing the "grouping line" after editing it could be awkward

**Comment by alexsb** [comment]
When I increase the "row with grouping names" and decrease it again, the GUI doesn't update correctly:

![grouping](https://f.cloud.github.com/assets/2039375/887011/98e74792-f9f4-11e2-890b-b147664aa61e.png)

**Comment by alexsb** [comment]
This is caused by the side-effect change of the number of header rows - which I didn't see. A non-issue.
