### ISSUE TITLE
there is currently no way to figure out how many samples/patients are in a stratification

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1470]
We only show total number of samples loaded (selection view) and number of samples in the data set (data set info view) but I need to know how many of those samples are covered by a given stratification.

**Comment by ngehlenborg** [comment]
The number of elements shown in the LineUp view is what I want, but it is pretty inconvenient to look it up there.

We also need to take into account that a stratification might contain more samples than the matrix. What we really want to display somewhere is the total number of samples shown in StratomeX as well as the number of elements in the stratification, something like this:

**`<sample>` Statistics**
only in matrix: x_m
in both matrix and stratification: x
only in stratification: x_s

**Comment by alexsb** [comment]
This was discussed in #772 which was closed because no one was interested. 

I don't understand what you mean by "the total number of samples loaded (selection view)"?

I think this would probably be an option to either show in the dataset info view - but there's pretty a lot of data there already - or in a separate header brick view. 

Probably the easiest way to deal with this is to select a whole column.

**Comment by ngehlenborg** [comment]
The selection view shows the total count (= union across multiple data domains) of all sample ids loaded (for a given sample id type, e.g. TCGA_SAMPLE)

**Comment by alexsb** [comment]
I've implemented PerspeciveInfos:

![perspective_info](https://f.cloud.github.com/assets/2039375/837988/b3db42e8-f313-11e2-8fe3-03c95b5ad934.png)

Right now they are updated for every brick you select, i.e., they show the info for the overall stratification if you click the header, else they show the data about the brick. It also shows the percentage relative to the dataset size. 

I can change this if we always want to show the stratification info. We could also update the histogram according to the selected stratification. 

Concerning the "only in stratification" info: We don't store this at the moment when the stratification is converted for a specific dataset.

**Comment by alexsb** [comment]
Added unmapped data to info view: 
![unmapped](https://f.cloud.github.com/assets/2039375/838236/b70f0f98-f319-11e2-983c-48aebe4dc166.png)

This shows how many elements were lost due to a conversion of stratification. I'm not thrilled by this information taking up two rows though. Maybe we could show it as a tooltip for the counts if unmapped is not 0. Currently tooltip provides info on this as it's also hard to understand. 

This is implemented for the convertForeign stuff. - does this occur some other place? @ngehlenborg  what was your original intention there?

**Comment by sgratzl** [comment]
the unmapped field is really hard to interpret without knowing the details. I'm not sure whether this is really useful. In the same sense, we would have to highlight multi mappings.

**Comment by alexsb** [comment]
I'm adding the unmapped as tool-tip on the number of samples/genes

**Comment by mstreit** [comment]
OK

**Comment by alexsb** [comment]
A little hidden, but here it is: 

![unmapped](https://f.cloud.github.com/assets/2039375/849713/bbb876dc-f478-11e2-91e6-c5c855cd0936.png)
