### ISSUE TITLE
selection is messed up when re-ordering results

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1493]
To reproduce: 
1.  Perform query into CNV based on overlap. 
2.  Reorder based on CNV metrics (here: high level amplification)
3. Scroll to top and select first result based on new ranking.

![screen shot 2013-07-16 at 10 09 03 am](https://f.cloud.github.com/assets/1216518/805149/881649a6-ee21-11e2-9008-17c34dbc8d47.png)

Related to #1465.

**Comment by sgratzl** [comment]
the problem is how to compute the intersection between hit and query/ies. 

the strategy that issued this ticket, just takes the current ranking criteria into account. If it refers to a stratification/group use that otherwise select all

the old/reimplemented strategy takes all columns before the first snapshot into account. The problem is that if you have multiple query columns, the selection may get too small

**Comment by ngehlenborg** [comment]
What about always using the (last) query column as triggered by the user through the TourGuide, independently of the ordering? That is what I would expect to see.
