### ISSUE TITLE
SelectAble HistogramElement

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1523]
see also #1520 

currently the histogram element is stupid. It could: 
1. listen to selections and visualize the selected items in the bins using some kind of stacked bars
2. have selectable bins (e.g. only in the single column case, like gender)
3. hover + tooltips (percentages) for bins
4. in a high detail mode include axis

**Comment by alexsb** [comment]
Yes, but most of this makes sense only for histograms that summarize either one row or one column in a dataset and are useless for histograms that aggregate a whole table. 

The problem there is the question on what you select: the row, the column or the cell. I assume that in a reasonable large dataset there will be a value in a bin in every row  and in every column, so selecting rows or columns (e.g. samples or genes) doesn't make sense. You'd have to select the cells - which is something we currently don't do (but maybe should?)

This problem is relevant for points 1 & 2. 

I agree with 3. 

For 4 - you mean labels? That used to be with the SWT GUI, but should be moved to the GL, yes.

**Comment by sgratzl** [comment]
I implemented for the categorical case a distribution element that shows the distributions of the categorical element in various forms: pie, stacked bar, histogram. 

all of them support simple tooltips (name, count and percentage) and a hover effect.
