### ISSUE TITLE
add progress indicator, message, version number to splash screen before opening project wizard

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1637]
Empty space at the bottom of the splash screen makes the screen look off center.

Message could be "Launching ..." or "Launching Project Wizard ..."

**Comment by sgratzl** [comment]
I don't think this is possible. 

The splash screen itself is displayed by the launcher, whereas the progress bar is rendered afterwards while the application is already loading. 

The problem is that at this point the workbench.xmi (open views,...) has been already loaded, but since we want to overwrite after the user selected the project, we have a problem. 

we could fake some parts by rendering something in the splash screen image, which will be overridden with the progress bar, afterwards

**Comment by sgratzl** [comment]
as I said, I don't think that I can render something onto the splash before the wizard appears. 

Therefore I tried to manipulate the splash screen itself, indicating the progress bar:

![caleydo-3-regular](https://f.cloud.github.com/assets/4129778/1186106/b38ad04a-22e0-11e3-9e3e-6d5efa1ccd9f.png)

rfc

**Comment by ngehlenborg** [comment]
Works fine.
