### ISSUE TITLE
only apply external score filters to data types for which they were loaded

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1656]
Right now they are applied to all data types, which means that switching to a new data type may result in an empty list.

To reproduce:
- activate mutations (only)
- load external score and associate with GENE, e.g. q-values
- apply filter, e.g. q <= 0.1
- deselect mutations
- select mRNA-seq: nothing will be shown until q-value column/filter is closed (using red "X" button)

**Comment by sgratzl** [comment]
just to describe what is running in the background: 
1. you load the q-values for Genes, with e.g. mean combiner
2. you want to have the score for a stratification of mRNA-seq
3. score will be computed. 
   mRNA-seq has in the dimension Gene so the final result is the mean of all gene scores of this perspective. 
4. since most of the genes have a q-value ~1 -> mean ~ 1
5. filter will be applied -> row will be filtered out

So three options: 
1. compute the score if the record or dimension idtype is right (now)
2. compute the score iff the idtype is the right one ( GENE -> mutation + copy number)
3. compute the score if the it exact the right one (loaded for GENE -> mutation)

**Comment by sgratzl** [comment]
> So three options:
> 
> ```
> compute the score if the record or dimension idtype is right (now)
> compute the score iff the idtype is the right one ( GENE -> mutation + copy number)
> compute the score if the it exact the right one (loaded for GENE -> mutation)
> ```

rfc

**Comment by ngehlenborg** [comment]
I think option 2 is appropriate because the score is associated with the GENE identifier. 

However, since the user loads the external scores for a specific datatype (here: mutations), the mental model of the user might be off. We should consider this in future work.

**Comment by ngehlenborg** [comment]
> We should consider this in future work.

That means that we should treat data matrices, stratifications, and scores as equal partners, e.g., in Crossword, and move away from the datatype-centric view.
