### ISSUE TITLE
Work out way for assigning non-genetic data to Entourage/enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1663]
With the new data assignment strategy for Entourage (see #1648 and #1662) we also need a new way to assign non-genetic  data to Entourage. Currently we use IC 50 drug values here, but any non-genetic patient-specific value is possible. 

I suggest we use a second lineup instance for non-genetic data. For the drug case this would be listing a single dataset plus each drug as a line in lineup.

**Comment by cpartl** [comment]
We also discussed another solution, which was to add the non-genetic datasets to the list of genetic datasets, but separated below them. The issue that remains is how we can select individual drugs, or, dimensions in general (which can be quite numerous).

**Comment by sgratzl** [comment]
I can't see the differences to the LineUp Others view. Assuming that the drugs datadomains is inhomogenous.

**Comment by alexsb** [comment]
It's not necessarily but possibly inhomogeneous, but we can treat it as such. I think the biggest problem with an "other lineup" is that it's not very accessible if we don't provide a wizard as we do in StratomeX. So if we use a separate lineup we need to integrate wizard components in enRoute.

**Comment by alexsb** [comment]
We decided to use the other lineup as it is used in StartomeX. In addition we want a button in the other lineup that highlights in which view the data is assigned. Also, we should be able to directly assign it to the appropriate view via context menu.

**Comment by sgratzl** [comment]
> Also, we should be able to directly assign it to the appropriate view via context menu.

that is not possible in the current version, since the adapter implementation will be created on the fly for the current selected view.

**Comment by sgratzl** [comment]
there is now another adapter for entourage for the others LineUp view. But I have no idea, how to use the selection to show the data in Entourage -> @cpartl, can you help me, please

**Comment by cpartl** [comment]
@sgratzl Yes, I will start by adapting entourage/enroute for that as I figured there is some more stuff to do than I thought. Am I right to assume that Tourguide will provide one `TablePerspective` for each dimension (e.g. age, days to death etc.) that was selected by the user?

**Comment by sgratzl** [comment]
> @sgratzl Yes, I will start by adapting entourage/enroute for that as I figured there is some more stuff to do than I thought. Am I right to assume that Tourguide will provide one TablePerspective for each dimension (e.g. age, days to death etc.) that was selected by the user?

Similar to the stratification LineUp you can cast the `AScoreRow` to a `ITablePerspectiveScoreRow`. The TablePerspective will be 1-dimensional of the selected inhomogeneous column with all records.

**Comment by cpartl** [comment]
@sgratzl We need a few changes to "Other Lineup" for Entourage:
- It should display all non-genetic datasets that have a Record- or Dimension Perspective with the ID Category `DataMappingState.getExperimentalDataIDCategory()`; The Records or Dimension with the other ID Category should then be listed for each dataset
- It should be possible to select/deselect the records/dimensions similar to the groups in the "Stratification Lineup" of Entourage

**Comment by sgratzl** [comment]
in the current version the Other LineUp lists all

_inhomogenous data domains_ and of the all columns (aka. single column table perspectives), which are _real_ or _natural numbers_

So I don't get your point, what should (not) be shown in this LineUp view

**Comment by cpartl** [comment]
It should not show less, it should show more. It should consider ALL non-genetic data domains (also the homogeneous ones) with the restrictions descibed above. For example, the Compound dataset for the CCLE project is currently not shown in the Other Lineup.

**Comment by sgratzl** [comment]
lineup part blocked by: #1718

**Comment by sgratzl** [comment]
> It should display all non-genetic datasets that have a Record- or Dimension Perspective with the ID Category `DataMappingState.getExperimentalDataIDCategory();` The Records or Dimension with the other ID Category should then be listed for each dataset

I don't fully get it. Will `DataMappingState.getExperimentalDataIDCategory();` always return the same id category or can it change. i.e. do I need to update the data domains, when "something" happen. If yes, define what this something is, and how I can get be notified about that.

> It should be possible to select/deselect the records/dimensions similar to the groups in the "Stratification Lineup" of Entourage

can you give me an exact example, what should be presented in what way using one of the sample projects?

**Comment by cpartl** [comment]
> I don't fully get it. Will DataMappingState.getExperimentalDataIDCategory(); always return the same id category or can it change. i.e. do I need to update the data domains, when "something" happen. If yes, define what this something is, and how I can get be notified about that.

For the moment it will always return the same id category during an entourage lifetime. The idea behind this is that in future, we will probably want the user to be able to select the id category for which the experimental data should be shown. I guess we will implement this flexibility at some point (would probably also be a good idea for stratomex or other views -> unique interface), but probably not for this release. 
However, what should happen if the id category changes: 
in the stratification lineup: 
- only genetic datasets that also have this id category should be shown
- only stratifications for this id category should be shown

for non-genetic lineup:
- only non-genetic datasets that also have this id category should be shown
- the list of records (or dimensions) should update so that it shows those of the other id category

As this is not yet implemented, i do not really know yet how to inform lineup about that, but I guess it will be some kind of event?

> can you give me an exact example, what should be presented in what way using one of the sample projects?

For the ccle project:
There is only one dataset that meets the criteria, which is "Compound - Cell Effect"
If you select this dataset, the list of records (or dimensions) should show the compound names, i.e., Erlotinib, Lapatinib, 17-AAG...
This list should look and behave like the groups list in the stratification lineup, i.e., there should be checkboxes to select and add compound to entourage or deselect and remove a compound. There should also be this select all/none checkbox.

For a tcga sample project (no matter if all or sampled):
There is only one dataset that meets the criteria, which is "Clinical"
If you select this dataset, the list of records (or dimensions) should show all clinical variables (age, days to death etc) also including non-numeric ones (sex, race etc).

For each of our sample projects we only have one dataset that should be displayed, however, there could be more. So in this list of records (or dimensions) the records of the currently selected dataset should be shown.

**Comment by alexsb** [comment]
I think this works great now. Thanks everyone! Closing.
