### ISSUE TITLE
Dataset Info View should update with every selection. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1737]
When not using the DVI or StratomeX it's pretty hard to get a Dataset Info View Update currently. 

Should work:
- by clicking a mapped pathway node
- by clicking a group in enRoute
- by clicking a bar in enRoute

**Comment by cpartl** [comment]
@alexsb I currently implemented it the following way: 
- when selecting a pathway node, the mapped table perspective is used
- when selecting a group or bar in enRoute, the whole associated datadomain is used

For the group captions it might be a bit ambiguous if you have contextual table perspectives, which belong to a different dataset. in case of column and group captions you might also want to trigger the update for only some tablePerspective instead of the whole dataset, but it is not really clear what tableperspective this should be and it might even not exist (yet).

**Comment by alexsb** [comment]
OK, discussed this, it works for me as-is.
