### ISSUE TITLE
Element Layout Enhancements

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#865]
collection of ides for element layout enhancements:

Basic Elements: 
- Button: 
  - Renderer for Hover,Down 
  - Picking-Wrapper -> Event...
  - automatic Tooltip support 
  - 
- Togglebutton: Renderer für Hover,A,B
- Scrolled Elements: 
  -> ~ Minsize needed
  think of: 
- extract Layout Arrangement to "Layouter" similar to SWT, AWT
- Renderer indepenent of Element and use some context parameter
- add View as part of the Layout Manager -> up to now needed for pickables
- element layouts parent link, e.g. on an invalidate of a child also the parent invalidate,...
- special picking mode, e.g. text don't need to be rendered but just the box around...

**Comment by cpartl** [comment]
- Take care about disposal of renderers and associated resources such as display lists or picking listeners. Maybe some automatic mechanisms within the layout.
- Think about refraining from using glTranslate for layouting and store position of renderers in the renderers. Instead of only setting width and height, set minX, minY and maxX, maxY. That way it is much easier to determine the real position of a renderer, which is often needed when anchor points are required (e.g. for connection bands). That way, renderers also become more independent from layouts.

**Comment by sgratzl** [comment]
- what about independent display lists for picking render pass and normal pass. e.g. if the color changes the picking render pass can be still the same
  - texture renderer / caleydo texture renderer should have a pool of available text sizes and should automatically select the best fitting text renderer according to the requested text size
  - think of specifiying text sizes in pt / px instead of by specifying the height of the element layout
  - picking: would be great if the handling of the picking / picking listener would be part of the to pick element. ala on a Button: onClickListener,...
  - a init phase / run would be good too, e.g. that all the used textures are loading during intialization and not on the first run. -> maybe a shared gl context for the big textures ala pathways?

**Comment by sgratzl** [comment]
proposal of new element architecture in r5829

**Comment by alexsb** [comment]
I assume this is resolved in layout2
