### ISSUE TITLE
External loading of cluster based quality metics

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#900]
For instance silhouette values

**Comment by sgratzl** [comment]
is there in caleydo a meaning / identifier for cluster names or are the just the labels of the corresponding group? 

What I mean is that do I have to compare Labels or is there a more intelligent way?

I assume you want a dialog like: 
 Data Domain -> Load GENE Stratifaction Group Metric -> Selection of Stratification -> use can upload a file with GROUP_NAME;score

which means we have an ID Category, but instead of an ID Type the Stratification Combo

**Comment by alexsb** [comment]
There is no meaning or identifier for the clusters other then the labels. What's the format of these files? @mstreit  Do we have an example?

**Comment by mstreit** [comment]
the clustering report can be found here: http://gdac.broadinstitute.org/runs/analyses__2013_03_26/reports/cancer/GBM/copynumber/clustering_cnmf/nozzle.html
the links at the bottom of the report point to the files containing the quality measures such as silhouette values etc.:
http://gdac.broadinstitute.org/runs/analyses__2013_03_26/data/GBM/20130326/gdac.broadinstitute.org_GBM-TP.CopyNumber_Clustering_CNMF.Level_4.2013032600.0.0.tar.gz

the clusters are identified by their number (starting from 1).
