### ISSUE TITLE
Make TCGA cal file generator work with new categorical data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#960]
This way we get many more clinical parameters for TCGA data.
However, we need a white list which parameters are actually interesting for a user.

**Comment by sgratzl** [comment]
wishlist: 
- boolean type, supporting: yes/no true/false 0/1 as input value, e.g. vitalstatus
- set categorical properties per column
- categorie columns supporting more that 10 categories -> CategoricalClassDescription.autoInitialize uses the 10 qualitative colors

**Comment by sgratzl** [comment]
draft r5790

**Comment by sgratzl** [comment]
notes: 
- resources/diseaseStudy.txt bzw. resources/diseaseStudySpecial.txt contain the list of tumor types and their long names
- resources/clinicalMapping.txt contains the list of all known clinical variables with their class and data type
- [http://code.google.com/p/google-gson/ gson] will now be used for JSON handling
- new post processing step after the data domain was loaded and before it will be saved again, e.g. for creating table perspectives

**Comment by sgratzl** [comment]
r5791

notes: 
- categorical definitions for mutations and copy number
- see also #1043 for the mutation data

**Comment by alexsb** [comment]
new in r5802
- set limit for auto-nominal categories to 10, strictly enforced. If more categories are desired you can't use auto-nominal. 

new in r5803
- Categorical properties can now be set per column

I don't think we should add a boolean type. We can't internally hold it as a boolean, since we 
- also need an "UNKNOWN" state
- have an implementation based on shorts

I don't think a separate boolean implementation is merited because of storage efficiency. 

Are there other arguments for a boolean category?
